version: '3.8'

services:
  api_service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    networks:
      - springapimysql-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/banking
      SPRING_DATASOURCE_USERNAME: Nazar
      SPRING_DATASOURCE_PASSWORD: strong_password
    depends_on:
      mysqldb:
        condition: service_started
    volumes:
      - .m2:/root/.m2

  mysqldb:
    image: "mysql:8.0"
    restart: always
    ports:
      - "3307:3306"
    networks:
      - springapimysql-net
    environment:
      MYSQL_DATABASE: banking
      MYSQL_USER: Nazar
      MYSQL_PASSWORD: strong_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uNazar", "-pstrong_password"]
      interval: 10s
      retries: 10

networks:
  springapimysql-net:


